USE [master]
GO

/****** Object:  Database [MeetingScheduleDb]    Script Date: 12/5/2025 01:31:29 ******/
CREATE DATABASE [MeetingScheduleDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'MeetingScheduleDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MeetingScheduleDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'MeetingScheduleDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.SQLEXPRESS\MSSQL\DATA\MeetingScheduleDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [MeetingScheduleDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [MeetingScheduleDb] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET ARITHABORT OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [MeetingScheduleDb] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [MeetingScheduleDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [MeetingScheduleDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET  ENABLE_BROKER 
GO

ALTER DATABASE [MeetingScheduleDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [MeetingScheduleDb] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [MeetingScheduleDb] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [MeetingScheduleDb] SET  MULTI_USER 
GO

ALTER DATABASE [MeetingScheduleDb] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [MeetingScheduleDb] SET DB_CHAINING OFF 
GO

ALTER DATABASE [MeetingScheduleDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [MeetingScheduleDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [MeetingScheduleDb] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [MeetingScheduleDb] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [MeetingScheduleDb] SET QUERY_STORE = OFF
GO

ALTER DATABASE [MeetingScheduleDb] SET  READ_WRITE 
GO

